version: '1.0'
steps:
  main_clone:
    title: Cloning main repository...
    type: git-clone
    repo: 'AayushShrestha14/PHPProject'
    revision: master
    git: github
  MyAppDockerImage:
    title: Building Docker Image
    type: build
    image_name: php-project-image
    working_directory: ./
    tag: master
    dockerfile: Dockerfile
